<?


define('INCLUDED', 1);
$PHP_SELF=htmlspecialchars($PHP_SELF);
$REMOTE_ADDR=(get_magic_quotes_runtime()) ? $REMOTE_ADDR: addslashes($REMOTE_ADDR);
if(isset($_SESSION['HAPPYBID_LOGGED_IN_USERNAME'])) 
	$_SESSION['HAPPYBID_LOGGED_IN_USERNAME'] = addslashes($_SESSION['HAPPYBID_LOGGED_IN_USERNAME']);
$HAPPYBID_TESTMODE = 'yes'; // Possible values: 'yes, 'no'		
#// ########################################################################################################

//-- This is the directory where passwd.inc.php file resides - requires ending slash

$main_path = ""; 
$include_path = "includes/"; 

//-- This is the directory where users pictures will be uploaded - requires ending slash
//-- Under Windows use something like C:\path\to\you\uploaddir\

$image_upload_path = "uploaded/"; 
$uploaded_path = "uploaded/"; 


//-- This string is added to passwords before generating the MD5 hash
//-- Be sure to never change it after the firt set up or 
//-- your users passwords will not work
$MD5_PREFIX = "asdad#@$erfwef";

/*
This is the log file generated by cron.php - insert the complete
file name (including the absolute path).
If you don't want to generate a log file for cron activity simply
leave this line commented.
*/
#$logFileName = "/var/www/auctions/logs/cron.log";
#$logFileName = "C:\path\to\cron.log";
/*
Set this to TRUE if you want cron to generates HTML output
BESIDES the cron file declared above. cron.php cannot generates
only HTML output.
*/
$cronScriptHTMLOutput = FALSE;

//if(isset($_COOKIE['USERLANGUAGE'])) {
//  echo "---".$language = $USERLANG = $_COOKIE['USERLANGUAGE'];  
//} else {
//  echo "===".$language = $USERLANG = $SETTINGS['defaultlanguage'];
//}

$language = $USERLANG = "EN";

include $include_path."settings.inc.php";
include $include_path."messages.".$USERLANG.".inc.php";
include $include_path."languages.inc.php";
?>
